### ISSUE TITLE
Paper download link

### ISSUE THREAD

**Issue by House-Leo** [happycaoyue/Pseudo-ISP#2]
Thanks for your awesome work!
But I can't find your paper in Google. Can you provide it for me?

**Comment by happycaoyue** [comment]
Thank you for your interest in our work. We will release this paper in ARXIV. About a week. I will add arxiv link in this repo.

**Comment by happycaoyue** [comment]
> 
> 
> Thanks for your awesome work!
> But I can't find your paper in Google. Can you provide it for me?

https://arxiv.org/pdf/2103.10234v1.pdf

**Comment by House-Leo** [comment]
> > Thanks for your awesome work!
> > But I can't find your paper in Google. Can you provide it for me?
> 
> https://arxiv.org/pdf/2103.10234v1.pdf

Thanks a lot!
